### ISSUE TITLE
他のタスクについて

### ISSUE THREAD

**Issue by 38cyclamen** [Ashiheart/4dc21summer-team4#10]
巨大生物の動作（移動、速度設定、接触判定(仮)、アニメーション等）の今のところできることが大体終わったので何かほかにした方がいいこととかありますか?

**Comment by Ashiheart** [comment]
うおおお疲れ様です!
タイトルシーンの配置等の作業をお願いはしたいのですが、僕自身が今からバイトなので22時までP班は休憩にしちゃいましょうｗ
