### ISSUE TITLE
Resolve conflicts before Mergeについて

### ISSUE THREAD

**Issue by pekepekee** [Ashiheart/4dc21summer-team4#11]
アニメーションを追加してコミットしてプルしようとしたら以下のような文が出てきました。
![image](https://user-images.githubusercontent.com/80317395/128470239-ecd655f4-b6ad-4671-893d-03759407149d.png)
これの解決策を調べてもいまいちわからなかったので解決方法を教えてほしいです。

**Comment by Ashiheart** [comment]
コンフリクトですね!
これは自身のPCで書き換えたTagManager.assetがリモート(サーバー)上でも別に書き換えられていて、どちらを優先するべきか分からなくなっている状態です。

よく出るエラーですが、修正は若干面倒なのでバイト終わった22時以降に一緒に解決したいです。それまで休憩して頂ければ!



一応以下に対応方法だけ殴り書きします。読まなくて大丈夫です。

一番手っ取り早いのはissue #9 のようにコミットを取り消してからpullしてしまう方法ですが、作業内容は消えてしまいます。

次に考えられる方法はTagManager.assetを自分の手で直接編集する方法です。これが正道なのですが、Unityのファイルをエディタで弄るのはめんどうですよね...

**Comment by pekepekee** [comment]
issue#9と同じやり方をしたら無事解決しました。ありがとうございます！

**Comment by Ashiheart** [comment]
解決しちゃったんかすご!
こちらこそ対応ありがとうございます。
