### ISSUE TITLE
ちくわを大きくする処理について

### ISSUE THREAD

**Issue by pekepekee** [Ashiheart/4dc21summer-team4#12]
タラを取るとちくわが大きくなる処理に詰まっています。助けてください。

**Comment by 38cyclamen** [comment]
どんな感じにつまっていますか教えてください。(どうやって大きくしようかみたいな)
多少ですが力になれるかもです。

**Comment by pekepekee** [comment]
タラを3個取ったら小さいちくわのオブジェクトから大きいちくわのオブジェクトに変えたいのですがうまくいきません。以下の動画のようになってしまいます。

https://user-images.githubusercontent.com/80317395/128529500-9203c7db-4b57-4c26-a08d-76b2442a10e9.mp4

**Comment by pekepekee** [comment]
出来ました。

https://user-images.githubusercontent.com/80317395/128531393-5587dffa-54bb-4996-bd3c-5946c4530662.mp4

**Comment by Ashiheart** [comment]
すご！てか動画載せられるの知らんかった...
LGTM!!!

**Comment by 38cyclamen** [comment]
できましたか。力になれず申し訳ない…

**Comment by Ashiheart** [comment]
そういえば言い忘れてましたごめんなさいいい
issueの内容が完了したときは↓にある「Close Issue」を押しちゃってくださいませ！
