### ISSUE TITLE
体力について

### ISSUE THREAD

**Issue by pekepekee** [Ashiheart/4dc21summer-team4#13]
オブジェクトに接触すると体力は減るのでしょうか。また、もしオブジェクトに接触したときに体力が減るなら動物に触れたときはより多くの体力が減るようにしたほうがいいですか?

**Comment by Ashiheart** [comment]
これなんだけど、動物に触れたら即死にしちゃうのも妥当な気がするｗ
@gaku-code @38cyclamen みんなの意見も聞きたいお

**Comment by 38cyclamen** [comment]
私は動物に触れると一発アウト=動物は即死ライン
的な意識で作っていたので即死でいいと思います。

**Comment by pekepekee** [comment]
分かりました。また、障害物に触れて減る体力を小さいちくわの体力が5として大きいちくわの体力は10として実装してもいいですか？

**Comment by gaku-code** [comment]
僕も動物に触れると即死のほうがいいと思うので、大丈夫です。

**Comment by Ashiheart** [comment]
> 分かりました。また、障害物に触れて減る体力を小さいちくわの体力が5として大きいちくわの体力は10として実装してもいいですか？

いいと思う！
ついでに、小さいちくわの残り体力が2とか1だったとしても、大きいちくわになったら体力10にしちゃってよさそう！(実装そのほうが楽だし)

**Comment by pekepekee** [comment]
> > 分かりました。また、障害物に触れて減る体力を小さいちくわの体力が5として大きいちくわの体力は10として実装してもいいですか？
> 
> いいと思う！
> ついでに、小さいちくわの残り体力が2とか1だったとしても、大きいちくわになったら体力10にしちゃってよさそう！(実装そのほうが楽だし)

その方向で実装します。
