### ISSUE TITLE
ゲームシーン中のUIまわりについて

### ISSUE THREAD

**Issue by Ashiheart** [Ashiheart/4dc21summer-team4#15]
体力を明示するならばHPバーを作ってしおうと思うのですが、他に必要なUIって何かありますかね...?

**Comment by pekepekee** [comment]
HPバーだけでいい気がします。

**Comment by Ashiheart** [comment]
リアルタイムなアクションゲームだから見るところ多いと忙しいしね！ありがとう

**Comment by 38cyclamen** [comment]
私も特に必要ないと思っています。

**Comment by Ashiheart** [comment]
了解したー他に追加はなしでいこう！
